[
    {
        "name": "ps_l",
        "value": "1",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1781082492,
        "storeId": null
    },
    {
        "name": "datr",
        "value": "99AZaAu6qXQwl5pYY0gs8GTo",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1781082359,
        "storeId": null
    },
    {
        "name": "fr",
        "value": "1cGBqA94kC3l8gZcm.AWfrm4PxespzKPtIDHh-hSvF3AdOpe9yIIBVFbXOF3d2tunqYHA.BoGlYR..AAA.0.0.BoGlaT.AWclwfzC_l8HJbwsfbR0S68hY5c",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1754332563,
        "storeId": null
    },
    {
        "name": "vpd",
        "value": "v1%3B786x393x2.727272727272727",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1751740417,
        "storeId": null
    },
    {
        "name": "xs",
        "value": "8%3AyoVJDY-ebLDU7w%3A2%3A1746526063%3A-1%3A8765%3A%3AAcVmeFrpjM5-8L_pAVM7QEjLZKHZyKqp4l3CWAZs7g",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1778092434,
        "storeId": null
    },
    {
        "name": "fbl_st",
        "value": "100435069%3BT%3A29109273",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "strict",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1778092417,
        "storeId": null
    },
    {
        "name": "locale",
        "value": "en_US",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1747130790,
        "storeId": null
    },
    {
        "name": "c_user",
        "value": "100029565127453",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1778092434,
        "storeId": null
    },
    {
        "name": "presence",
        "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1746556573369%2C%22v%22%3A1%7D",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": true,
        "firstPartyDomain": "",
        "partitionKey": null,
        "storeId": null
    },
    {
        "name": "dpr",
        "value": "2.727272727272727",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1747161369,
        "storeId": null
    },
    {
        "name": "ps_n",
        "value": "1",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1781082492,
        "storeId": null
    },
    {
        "name": "sb",
        "value": "99AZaIMtUWRAq3LIpDX87K7E",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": true,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1781086066,
        "storeId": null
    },
    {
        "name": "wd",
        "value": "980x1945",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "lax",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1747161369,
        "storeId": null
    },
    {
        "name": "wl_cbv",
        "value": "v2%3Bclient_version%3A2806%3Btimestamp%3A1746556416",
        "domain": ".facebook.com",
        "hostOnly": false,
        "path": "/",
        "secure": true,
        "httpOnly": false,
        "sameSite": "no_restriction",
        "session": false,
        "firstPartyDomain": "",
        "partitionKey": null,
        "expirationDate": 1754332417,
        "storeId": null
    }
]
